# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

image: busybox

pages:
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - Web
